# Generated by Django 2.2.7 on 2019-12-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20191204_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Artist is never deleted, his status changes to true', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/pictures/', verbose_name='profile picture'),
        ),
    ]
