# Generated by Django 2.2.7 on 2019-11-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('slug_name', models.SlugField(error_messages={'unique': 'An art piece with this slug name already exists.'}, unique=True, verbose_name='slug name')),
                ('name', models.CharField(max_length=150, verbose_name='art piece name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='art piece description')),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/art_pieces/pictures/', verbose_name='profile picture')),
                ('status', models.BooleanField(default=False, help_text='Art Piece is never deleted, his status changes to true', verbose_name='deleted')),
                ('sold', models.BooleanField(default=False, help_text='Art Piece is sold', verbose_name='sold')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artpieces', to='artists.Artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artpieces', to='categories.Category')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtPieceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('name', models.CharField(max_length=50, verbose_name='art piece tag')),
                ('art_piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='art_pieces.ArtPiece')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtPieceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('name', models.CharField(max_length=50, verbose_name='art piece detail name')),
                ('detail', models.CharField(max_length=100, verbose_name='art piece detail detail')),
                ('art_piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='art_pieces.ArtPiece')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
