# Generated by Django 2.2.7 on 2019-11-25 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art_pieces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='likes',
            field=models.ManyToManyField(related_name='artpieces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artpieces', to='orders.Order'),
        ),
    ]
