# Generated by Django 2.2.7 on 2019-11-25 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('art_pieces', '0002_artpiece_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artpieces', to='orders.Order'),
        ),
    ]
