# Generated by Django 2.2.7 on 2019-11-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_pieces', '0004_artpiecedetail_artpiecetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiecedetail',
            name='detail',
            field=models.CharField(default='', max_length=100, verbose_name='art piece detail detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artpiecedetail',
            name='name',
            field=models.CharField(max_length=50, verbose_name='art piece detail name'),
        ),
    ]
