# Generated by Django 2.2.7 on 2019-12-07 19:19

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('art_pieces', '0002_auto_20191125_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artpiece',
            old_name='status',
            new_name='deleted',
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='slug_name',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
