# Generated by Django 2.2.7 on 2019-12-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_pieces', '0003_auto_20191207_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiecedetail',
            name='art_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='art_pieces.ArtPiece'),
        ),
        migrations.AlterField(
            model_name='artpiecetag',
            name='art_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='art_pieces.ArtPiece'),
        ),
    ]
