# Generated by Django 3.0 on 2019-12-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_pieces', '0004_auto_20191209_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='art_pieces/pictures/', verbose_name='profile picture'),
        ),
    ]
