# Generated by Django 2.2.7 on 2019-11-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('first_name', models.CharField(max_length=30, verbose_name='artist first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='artist last name')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='artist biography')),
                ('website', models.URLField(verbose_name='artist website')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('address', models.CharField(max_length=255, verbose_name='artist address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/pictures/', verbose_name='profile picture')),
                ('is_active', models.BooleanField(default=False, help_text='Artist is never deleted, his status changes to true', verbose_name='deleted')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
